### PR TITLE
Add Pale Blue Accent Color from Android 10 Dark Mode for Android Pie

### PR DESCRIPTION
**Pull request by frachmadin**
Hi, sir.

Could you please add Pale Blue (#82B1FF) accent color from Android 10 dark mode for Android Pie?
Especially for V1.2. Due to dropped support for Pie on V2.0.

I really hope you can look into it. Thank you very much.

### CODE REVIEW

**Comment by ponces** [comment]
> Hi, sir.
> 
> Could you please add Pale Blue (#82B1FF) accent color from Android 10 dark mode for Android Pie?
> Especially for V1.2. Due to dropped support for Pie on V2.0.
> 
> I really hope you can look into it. Thank you very much.

I'll try to add it this week.
It would be better if you had open an issue instead of a pull request.
For Android 10, you can get this updated version - https://github.com/ponces/sac/releases/tag/v2.0
But it also doesn't include that color. I'll update it too.

**Comment by ponces** [comment]
> I'll try to add it this week.
> It would be better if you had open an issue instead of a pull request.
> For Android 10, you can get this updated version - https://github.com/ponces/sac/releases/tag/v2.0
> But it also doesn't include that color. I'll update it too.

Could you please test [this version](https://drive.google.com/open?id=1DxlLGlk7NGFl5RJYwhfGsPhl0MLK2coH)?
Note that it only supports Android 9.

**Comment by frachmadin** [comment]
> I'll try to add it this week.
> It would be better if you had open an issue instead of a pull request.
> For Android 10, you can get this updated version - https://github.com/ponces/sac/releases/tag/v2.0
> But it also doesn't include that color. I'll update it too.

I do apologize, sir. It's my first time digging into github.
I had tested v2.0 on Android 10 too. As far as I remember, it works perfectly. But, since its ROM currently is not stable enough, I decided to downgrade to Pie again.

> Could you please test [this version](https://drive.google.com/open?id=1DxlLGlk7NGFl5RJYwhfGsPhl0MLK2coH)?
> Note that it only supports Android 9.

Sir, I have been testing your test version on Pie. It works perfectly! I got no issue so far. Thank you very much, sir.

**Comment by ponces** [comment]
> > I'll try to add it this week.
> > It would be better if you had open an issue instead of a pull request.
> > For Android 10, you can get this updated version - https://github.com/ponces/sac/releases/tag/v2.0
> > But it also doesn't include that color. I'll update it too.
> 
> I do apologize, sir. It's my first time digging into github.
> I had tested v2.0 on Android 10 too. As far as I remember, it works perfectly. But, since its ROM currently is not stable enough, I decided to downgrade to Pie again.
> 
> > Could you please test [this version](https://drive.google.com/open?id=1DxlLGlk7NGFl5RJYwhfGsPhl0MLK2coH)?
> > Note that it only supports Android 9.
> 
> Sir, I have been testing your test version on Pie. It works perfectly! I got no issue so far. Thank you very much, sir.

Thank you for your tests.
I applied the change in the Magisk official repo - v1.2.
I'll close this PR then.

**Pull request closed without merging**
